### ISSUE TITLE
Ability to provide password for users

### ISSUE THREAD

**Issue by nickw444** [ansible-city/users_and_groups#9]
It would be useful if a password could be passed onto the users module when creating the accounts:

http://docs.ansible.com/ansible/user_module.html

Cheers

**Comment by wojtek-oledzki** [comment]
PR #10 opened

**Comment by wojtek-oledzki** [comment]
#12 is finally building - no idea what went wrong with the previous two :(

**Comment by wojtek-oledzki** [comment]
released in v1.0.2
version v1.0 updated

**Comment by nickw444** [comment]
Thanks for this!
